# channels:
  # - anaconda
  # - conda-forge  # Include conda-forge channel
  # - defaults  
dependencies:
  # - python=3.11.6
  - conda-forge::tensorflow-cpu=2.12.1
  - numpy=1.26.4
  - pip:
      - streamlit==1.38.0
