# channels:
  # - anaconda
  # - conda-forge  # Include conda-forge channel
  # - defaults  
dependencies:
  # - python=3.11.6
  - conda-forge::tensorflow=2.12.1
  - conda-forge::scikit-learn=1.3.1
  - pip:
      - streamlit==1.38.0
      - numpy==1.26.4
